version: '3.8'

services:
  preprocess:
    build: 
      context: ./0_preprocess
      no_cache: true
    volumes:
      - ${DATA_DIR}:/data
    environment:
      - PATIENT_ID=${PATIENT_ID}
    command: "${PATIENT_ID} ${NUM_BOOTSTRAPS:-5}"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
    develop:
      watch:
        - action: sync+restart
          path: ./0_preprocess
          target: /app

  phylowgs:
    build:
      context: ./1_phylowgs
    volumes:
      - ${DATA_DIR}:/data
    environment:
      - DATA_DIR=/data
      - PATIENT_ID=${PATIENT_ID}
    command: "${PATIENT_ID} ${NUM_CHAINS:-5} ${NUM_BOOTSTRAPS:-5}"
    depends_on:
      preprocess:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 16G

  aggregation:
    build:
      context: ./2_aggregation
    volumes:
      - ${DATA_DIR}:/data
    environment:
      - PATIENT_ID=${PATIENT_ID}
    command: "${PATIENT_ID} ${NUM_BOOTSTRAPS:-5}"
    depends_on:
      phylowgs:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8G

  markers:
    build:
      context: ./3_markers
    volumes:
      - ${DATA_DIR}:/data
    environment:
      - PATIENT_ID=${PATIENT_ID}
    command: "${PATIENT_ID} ${NUM_BOOTSTRAPS:-5}"
    depends_on:
      aggregation:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8G

volumes:
  vis_mase_phi_data:

x-config: &config
  exit-code-from: phylowgs